In [2]:
# set up environment
import numpy as np

In [4]:
arr1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(arr1)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [29]:
arr1 = np.zeros(10, dtype=int)
arr2 = np.ones((3, 5), dtype=float)
arr3 = np.full((3, 5), 3.14)        # whole arrays filled with 3.14
arr4 = np.arange(0, 20, 2)          # between 0 and 20, by 2
arr5 = np.linspace(0, 1, 5)         # 5 values evenly spaced
arr6 = np.random.random((3, 3))     # random numbers between 0-1
arr7 = np.random.normal(0, 1, (3, 3))   # random numbers with mean = 0 & sd=1
arr8 = np.random.standard_normal((3, 3))    
arr9 = np.random.randint(0, 10, (3, 3)) # random integers <1,10)
arr10 = np.eye(3)                           # identity matrix

for x in range(1, 20): 
    try:
        print(eval('arr' + str(x)), end='\n')
    except NameError:
        pass

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.64078473 0.73611064 0.94208347]
 [0.04020064 0.87989618 0.96535885]
 [0.93871317 0.23291737 0.93558008]]
[[-0.27603745 -1.05040579  0.23427608]
 [ 0.7839172   1.20584358  1.23734226]
 [ 1.02048749 -0.05288287 -0.18399344]]
[[-0.28119239  0.03891919 -0.6814195 ]
 [ 0.69182654 -0.51565771  0.58687182]
 [ 0.55457213 -0.89024379  1.166893  ]]
[[8 3 4]
 [1 9 7]
 [3 1 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
# Array attributes
np.random.seed(0)       # seed (freeze) for reproductivity
arr1 = np.random.randint(10, size=10)
arr2 = np.random.randint(10, size=(3, 4))
arr3 = np.random.randint(10, size=(3, 4, 5))
for i in range(1, 4):
    array = eval('arr'+str(i))
    print('arr'+str(i), '\t|ndim:', array.ndim, '\t|shape:', array.shape, '\t|size:', array.size, '\t|dtype:', array.dtype, 
          '\t|itemsize:', array.itemsize, 'bytes', '\t|nbytes:', array.nbytes, 'bytes')

arr1 	|ndim: 1 	|shape: (10,) 	|size: 10 	|dtype: int32 	|itemsize: 4 bytes 	|nbytes: 40 bytes
arr2 	|ndim: 2 	|shape: (3, 4) 	|size: 12 	|dtype: int32 	|itemsize: 4 bytes 	|nbytes: 48 bytes
arr3 	|ndim: 3 	|shape: (3, 4, 5) 	|size: 60 	|dtype: int32 	|itemsize: 4 bytes 	|nbytes: 240 bytes


In [57]:
# Indexing
print(arr2)
print('0,0:', arr2[0, 0])
print('2,0:', arr2[2, 0])
print('2,-1:', arr2[2, -1])
arr2[0, 0] = 99
print(arr2)

[[7 6 8 8]
 [1 6 7 7]
 [8 1 5 9]]
0,0: 7
2,0: 8
2,-1: 9
[[99  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]]


In [76]:
print(arr1, arr1[::-1], sep='\n')
print('', arr2, arr2[:2, :3], sep='\n')
print('', arr2[:3, ::2], sep='\n')
print('', arr2[::-1, ::-1], sep='\n')     # reversed order of full matrix
print('', arr2, arr2[:, 2], arr2[1, :], sep='\n')            # only 3rd column, only 2nd row

[5 0 3 3 7 9 3 5 2 4]
[4 2 5 3 9 7 3 3 0 5]

[[99  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]]
[[99  6  8]
 [ 1  6  7]]

[[99  8]
 [ 1  7]
 [ 8  5]]

[[ 9  5  1  8]
 [ 7  7  6  1]
 [ 8  8  6 99]]

[[99  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]]
[8 7 5]
[1 6 7 7]


In [80]:
# how array views works
print(arr2)
sub_x2 = arr2[:2, :2]
sub_x2[0, 0] = 0       # it is view of arr2
print(arr2)
# what happens when we copy
sub_x2 = arr2[:2, :2].copy()
sub_x2[0, 0] = 99
print(arr2)

[[0 6 8 8]
 [1 6 7 7]
 [8 1 5 9]]
[[0 6 8 8]
 [1 6 7 7]
 [8 1 5 9]]
[[0 6 8 8]
 [1 6 7 7]
 [8 1 5 9]]


In [92]:
a = 3
arr2 = np.arange(1, a ** 2 + 1).reshape((a, a))
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
# reshape using newaxis method
arr1 = np.array([1, 2, 3])
print(arr1.reshape(1, 3))
print(arr1[np.newaxis, :])
print(arr1.reshape(3, 1))
print(arr1[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
