In [2]:
import numpy as np

In [7]:
data1 = [1, 2.3, 3, 4]
arr1 = np.array(data1)
print(arr1, '\ttype:', arr1.dtype)

[1.  2.3 3.  4. ] 	type: float64


In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print('dimensions: ', arr2.ndim, '\tshape: ', arr2.shape, '\ttype: ', arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
dimensions:  2 	shape:  (2, 4) 	type:  int32


In [5]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[8.18753309e-280 0.00000000e+000 3.62633684e+228 3.98450716e+252]
  [8.12549907e-096 8.95402178e-096 1.96099265e+243 1.33733641e+160]
  [3.98452900e+252 8.82142681e+199 8.16814779e-096 6.32307098e+233]]

 [[1.96086537e+243 2.85274704e-109 6.19522232e+223 5.03734623e+180]
  [9.82395831e+252 8.37170577e-144 6.02182527e+151 9.30537465e+199]
  [2.20835466e-094 5.50028887e+247 1.56246488e+161 1.63789377e-152]]]


In [6]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
# Different data types for arrays:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1, 'type: ', arr1.dtype)
print(arr2, 'type:', arr2.dtype)

[1. 2. 3.] type:  float64
[1 2 3] type: int32


In [10]:
# Convert one Type to another:
arr3 = np.array([1, 2, 3])
arr4 = arr3.astype(np.float64)
print(arr4.dtype)

float64


In [19]:
# Math operations on vectors
arr5 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(arr5 * 1.25)
print(1/arr5)
arr6 = np.array([[3, 2, 1], [5, 4, 3]])
print(arr5, '\n', arr6)
print(arr5 < arr6)

[[1.25 2.5  3.75]
 [5.   6.25 7.5 ]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1 2 3]
 [4 5 6]] 
 [[3 2 1]
 [5 4 3]]
[[ True False False]
 [ True False False]]


In [43]:
# Indexing and slicing Arrays
arr7 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr7[5:8])
arr7[5:8] = 12
print(arr7)
arr_slice = arr7[5:8]
arr_slice[1] = 12345        # changing slice (view) is changing original arrays
print(arr7)
# 2 dimensions Indexing
arr8 = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])
print(arr8[0][3], '||', arr8[0, 3])
# 3 Dimensions Indexing
arr9 = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],[[9, 10, 11], [12, 13, 14], [15, 16, 17]]])
print(arr9)
arr9_slice = arr9[0]
arr9_slice[2][2] = 99       # changing slice (view) is changing original arrays
print(arr9)
# 2 Dimensions Slice
print('\n',arr8)
print(arr8[:1])
print(arr8[:1, 3:])
print(arr8[:, :1])
arr8[:, 2] = 0
print(arr8)

[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[    0     1     2     3     4    12 12345    12     8     9]
4 || 4
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7 99]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

 [[1 2 3 4]
 [6 7 8 9]]
[[1 2 3 4]]
[[4]]
[[1]
 [6]]
[[1 2 0 4]
 [6 7 0 9]]


In [60]:
# Mix indexing
names = np.array(['Bob', 'Joe', 'Joe', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print('1:', data)
print('2:', data[names == 'Bob', 2])
print('3:', data[names != 'Bob', 2])
print('4:', data[(names == 'Bob') | (names == 'Will'), 2])
# Setting values with Bolean arrays
data[data < 0] = 0
print('5:', data)
data[names != 'Joe', 2] = 7
print('6:', data)

1: [[-0.09257879  1.56181505 -0.1254231  -0.14348318]
 [ 1.45351534  0.24328424 -0.84388476  0.82593908]
 [-0.4767379  -0.66855922 -0.70047639 -0.03091558]
 [-1.54818195 -0.35469788  0.04521816 -1.48054601]
 [ 0.92431207 -1.76824769  0.97856629 -2.12647417]
 [-1.70214038 -0.7692129  -0.58455551  0.09693126]
 [-2.47787929 -0.87206049  1.49754132  0.99457648]]
2: [-0.1254231   0.04521816]
3: [-0.84388476 -0.70047639  0.97856629 -0.58455551  1.49754132]
4: [-0.1254231   0.04521816  0.97856629]
5: [[0.         1.56181505 0.         0.        ]
 [1.45351534 0.24328424 0.         0.82593908]
 [0.         0.         0.         0.        ]
 [0.         0.         0.04521816 0.        ]
 [0.92431207 0.         0.97856629 0.        ]
 [0.         0.         0.         0.09693126]
 [0.         0.         1.49754132 0.99457648]]
6: [[0.         1.56181505 7.         0.        ]
 [1.45351534 0.24328424 0.         0.82593908]
 [0.         0.         0.         0.        ]
 [0.         0.         7. 

In [72]:
# Fancy Indexing
data = np.empty((8, 4))
for x in range(8):
    data[x] = x
print('1:', data)
print('2:', data[[6, 0, 3, 1]])
print('3', data[[-3, -5, -7]])
data = np.arange(32).reshape((8, 4))
print('4:', data)
print('5:', data[[1, 5, 7, 2], [0, 3, 1, 2]])
print('6:', data[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

1: [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
2: [[6. 6. 6. 6.]
 [0. 0. 0. 0.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
3 [[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
5: [ 4 23 29 10]
6: [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [76]:
# Transponse
arr = np.arange(9).reshape((3, 3))
print(arr)
print(np.dot(arr, arr.T))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
